spring:
  config:
    activate:
      on-profile: prod

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://tnote.cnqgskwe8j3c.ap-northeast-2.rds.amazonaws.com:3306/tnote
    username: ENC(JzyjcuzEelC2sOIaQtTYVg==)
    password: ENC(c9Xw639YRtZOIa/GHt6GmPVOUAt4vQ4N)

  security:
    oauth2:
      client:
        registration:
          kakao:
            redirect-uri: "https://teacher-note.co.kr/login/oauth2/code/kakao"


  jpa:
    hibernate:
      ddl-auto: update


  data:
    redis:
      host: ENC(2iWE7eOjnkSr0xq3W5TgoPs+BoKEqcd2)
      port: 6379

api:
  career-key: ENC(Njc5lZRU/nXPNWZmufc0M8vAg1Qt0USuJIRm4k1xKP/euN2ALFEAaK84GDZqKqx0)
  call-back-url: "https://open.neis.go.kr/hub"

jasypt:
  encryptor:
    bean: jasyptStringEncryptor

custom:
  jwt:
    secret-key: ENC(bMRicSH/i3TIp8KYjWARwpMTOh4Uu0V/M2Q0mAm0jJI39RXGlBnHPYSdQENSakWU/nJ4S0db2ROcZLJrkBxXltK0OfM8dAk2bn6JYwa5/Uk=)

logging:
  level:
    p6spy: error
    org:
      springframework:
        security: warn
