server:
  port: 8080
  error:
    include-message: always
    include-binding-errors : always

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url : jdbc:mysql://localhost:3306/tnote
    username : ENC(sNTWYtkpLNv2PcXl/hRAyw==)
    password : ENC(NMexjONfc42kzjSxCDNKYQ==)

  devtools:
    livereload:
      enabled: false
    restart:
      enabled: false

  jpa:
    open-in-view: true
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        validator:
          apply_to_ddl : false
        format_sql: true
        use_sql_comments: true
        default_batch_fetch_size: 1000 # ?? ??? ??? ??? N+1? ???? ??? ???
    database: mysql

  security:
    user:
      name: root
      password: root

jasypt:
  encryptor:
    bean: jasyptStringEncryptor

# hibernate logging
logging:
  level:
    p6spy: info
    org:
      springframework:
        security: DEBUG
