server:
  port: 8080
  error:
    include-message: always
    include-binding-errors : always

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url : jdbc:mysql://localhost:3306/tnote
    username : ENC(e98vlO4+8hU/yWUikbrVmQ==)
    password : ENC(PJUmqFtWNJZM8LhyNmR18w==)

  devtools:
    livereload:
      enabled: false
    restart:
      enabled: false

  jpa:
    open-in-view: true
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        validator:
          apply_to_ddl : false
        format_sql: true
        use_sql_comments: true
        default_batch_fetch_size: 1000 # 배치 사이즈 조절을 통해서 N+1이 나더라도 최소화 시킨다
    database: mysql

  security:
    oauth2:
      client:
        registration:
          google:
            client-id: ENC(M2gQH3j/cP+s3ZUJN5nMAOf/ER6moYwaMmKXNuK4qp1eqzk9xDdR60LKKBEvKZTdFGwXvPhrm5ztHu1vgDInNlBD+kN7Va8ND6E6llM2at5FwVz44UYnTQ==)
            client-secret: ENC(nq0Htj/dHR2sd8Vrv+Dpblt3QI+pEKrowkXRIuhdbAyX5Lqx2Val72eNrgo86+qh)
            redirect-uri: "http://localhost:8080/login/oauth2/code/google"
            authorization-grant-type: authorization_code
            scope: profile, email
        provider:
          google:
            authorization-uri: https://accounts.google.com/o/oauth2/v2/auth?prompt=consent&access_type=offline
            token_uri: https://accounts.google.com/o/oauth2/token
            user-info-uri: https://www.googleapis.com/oauth2/v2/userinfo

custom:
  jwt:
    secret-key: ENC(9KBL0zD4YP0GMdjQzGlUfN7XZlkoiyetp4+zvdUPEKZ7XYGTX3OLIeDwiLAFKz84DhGVEnrM2E55OL40pvlkgC75rFwBjaw4Gy6bPMFnqzs=)

jasypt:
  encryptor:
    bean: jasyptStringEncryptor

# hibernate logging
logging:
  level:
    p6spy: info
    org:
      springframework:
        security: DEBUG