spring:
  config:
    activate:
      on-profile: prod

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://tnote.cnqgskwe8j3c.ap-northeast-2.rds.amazonaws.com:3306/tnote
    username: ENC(JzyjcuzEelC2sOIaQtTYVg==)
    password: ENC(c9Xw639YRtZOIa/GHt6GmPVOUAt4vQ4N)

  security:
    oauth2:
      client:
        registration:
          kakao:
            redirect-uri: "https://xn--9w3b15cw7a.xn--3e0b707e/login/oauth2/code/kakao"

  jpa:
    hibernate:
      ddl-auto: update

  data:
    redis:
      host: ENC(B+y0ZPd0Vhrf3rU7J8AnIuH3kJT9gxAY)
      port: 6379

jasypt:
  encryptor:
    bean: jasyptStringEncryptor

